### ISSUE TITLE
UDP Transport and Counters

### ISSUE THREAD

**Issue by gphat** [coursera/metrics-datadog#22]
When using the UDP transport instead of HTTP, metrics counters passed along to the local DogStatsD instance come out all wrong.

This is due to a breakdown between Metrics' concept of a counter and StatsD's. Since Metrics keeps up with the total value of the counter over all time and StatsD expects that each counter send in the flush interval is to be *accrued*.

In other words, when I set my reporter to send metrics via UDP to a default-configured DogStatsD every 20 seconds, the following occurs:
* metrics-datadog sends the counter's total value every 20 seconds (this isn't wonky)
* DogStatsD interprets my counters *total value* as the value to increment the metric
* DogStatsD normalizes the total counter value received in the flush period by the flush period's length (10 seconds by default)
* DataDog's charts interpret the rate *and* counters completely wrong.

So, for example, I make a counter that increases by 1 per second and report it every 10 seconds. Here's what I get!

![screenshot 2014-12-13 17 20 32](https://cloud.githubusercontent.com/assets/45159/5425820/c886d8be-82ec-11e4-8717-afec6852bfca.png)

The count is way off because it's going up via `n=10+20+30+…+k`. The rate is also off because it's dividing each incoming counter value by 10 and reporting that as the rate a la `1, 2, 3, n`.

This makes counters of no use when using the UDP transport.

Are there any clever tricks for fixing the reporting of counters that I'm not seeing or is this just an unfortunate, unconsidered side-effect of the recent UDP transport addition?

**Comment by nickdella** [comment]
Cool! Sorry for the delay in replying; I kinda checked out for the holiday break :)  I left some comments on the PR

**Comment by amalakar** [comment]
Hi, sorry for being late to the party. I have been away for the holiday break too. @gphat thanks for finding the bug. I haven't pushed the changes in our production and haven't tested it extensively, so missed this super important bug. 

I checked the pull request, I see that the UDPransport now maintains state of what it has seen, wouldn't using gauge of statsdclient instead would achieve the same? This would eliminate the need to maintain the state of last seen counters in the transport. Thoughts?

**Comment by gphat** [comment]
It would allow the metrics to get out but they'd be typed incorrectly. A counter wouldn't show up as a `c` but as a `g` and we'd lose the upsides of counters like per-second rates. This seems like a better solution over losing fidelity of metrics.

I do admit that I often see things that make this concession when generating metrics, since counters require state. I'm hoping we can do better!

**Comment by nickdella** [comment]
@amalakar Any reservations on merging #23 to address this issue vs using a gauge? If not, I'll merge and deploy a new version on Sunday night.

**Comment by amalakar** [comment]
@nickdella the pull request looks good to me. We should be good to merge, thanks for reviewing the changes.
