### ISSUE TITLE
Allow tags to be per Gauge/Counter instead of per-reporter

### ISSUE THREAD

**Issue by rtyler** [coursera/metrics-datadog#25]
I think the `Gauge` interface should allow for some customization of tags reported to Datadog on a per-Gauge basis.

**Comment by matlockx** [comment]
as far as I can see from the code you can give your metric name a suffix in this format 
```
[tagName:tagValue,tagName:tagValue,...]
```
and then you get your tags per metric.

https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/model/DatadogSeries.java#L22

https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/model/DatadogSeries.java#L31

**Comment by rtyler** [comment]
@matlockx whoa, I hadn't seen that code before! perhaps it's an easter egg ;)

Have you successfully used it before, or just happened upon it?

**Comment by matlockx** [comment]
:) haven't used it yet, just trying it out. let you know tomorrow how it works. in fact i was looking for something like that and stumbled over the code by accident... ;)

**Comment by matlockx** [comment]
works. blanks are converted to underscores and special chars are removed

**Comment by matlockx** [comment]
@rtyler wanna close it?

**Comment by jeffreymyers** [comment]
Should this feature be documented in the README.md?

**Comment by matlockx** [comment]
Would be a good idea expect if it is planned to remove it...

**Comment by nickdella** [comment]
Sorry, guys, my notifications for this project were getting black-holed. Glad you found the tag encoding/expansion "feature"!  We use it heavily at Coursera. I'll update the README soon then close this issue out.

**Comment by nickdella** [comment]
@matlockx @jeffreymyers @rtyler I added some clarity and guidance around how tag encoding here: https://github.com/coursera/metrics-datadog#tag-encoding-and-expansion . There's also https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/TaggedName.java to help with encoding tagged names. Feel free to update/improve to your liking. Thanks!

**Comment by matlockx** [comment]
Fine for me. Thanks a lot
