### ISSUE TITLE
Add note about HTTP vs UDP

### ISSUE THREAD

**Issue by benmccann** [coursera/metrics-datadog#36]
It'd be good to include a line in the README about when you'd use the HTTP reporter vs when you'd use the UDP reporter. I have some ideas, but want to be sure there isn't anything I'm overlooking and it'd help less savvy users.

**Comment by kevinsookocheff-wf** [comment]
I'm also curious about what the current retry semantics are for the HttpTransport (if there are any right now).

**Comment by nickdella** [comment]
@benmccann I'm cleaning up old and neglected bugs. Thanks for raising this!  We've historically used HTTP-based reporting at Coursera (I inherited this setup) and haven't had the need (or the time!) to change over to switch over to `dogstatsd` and UDP. As for those intentionally *not* running `dogstatsd`, I can could guess at reasons such as a general adversity to running agents, memory usage, stability, security or some other weird environment/platform conflict.  Please enlighten me with other reasons you know of and I'd be happy to update the documentation.

@kevinsookocheff-wf As for retries, I checked `fluent-hc` and it ends up doing [3 retries per DefaultHttpRequestRetryHandler](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpclient/4.3.6/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.java#121).  It would be nice to make this configurable given that connect and socket timeout are already configurable. 

As for how the Datadog API handles retries, I can only we can only guess, as this is not documented. The API may or may not be idempotent :/  Also, I do remember reading that Datadog does not support "backfilling" of older data, so I wonder how long you could hold metrics on the client-side before they become "stale" and are rejected by Datadog upon receipt (this would apply to both HTTP or UDP, I'd presume).  I'll try pinging support for some answers.

**Comment by alq666** [comment]
@nickdella I can take the API question: within the window where we process current data (< 4h) submitting the same point over and over again is idempotent in terms of storage and visualization (if it's a gauge). Of course that's different story if that same metric is used for alerting where a late point may change the results of the monitor evaluation.

Though if the retry is within tens of seconds, you're probably ok.

**Comment by nickdella** [comment]
@alq666 Awesome! This seems pretty sane to me.  Our HTTP transport should work well enough as-is, I think. In the case of a lengthy network partition or a Datadog ingestion outage, we will lose metrics. The only way to avoid this would be to buffer more data in memory. This would require a refactoring of the reporter, which currently does a blocking send from a single thread every N seconds. Implementation challenges aside, I'd be also wary of the memory bloat in buffering datadog POST requests for extended periods of time (e.g. 10s of minutes or more).  `dogstatsd` [would be a better choice](https://github.com/DataDog/dd-agent/wiki/Agent-Architecture#the-forwarder) for those who require a longer buffering/retry window.

@benmccann Let me know if you have any other thoughts on HTTP vs UDP and I'd be happy to write up a paragraph in the README

**Comment by benmccann** [comment]
No other thoughts. Thanks!
