### ISSUE TITLE
Is there a way to send events to Datadog.

### ISSUE THREAD

**Issue by arunbcodes** [coursera/metrics-datadog#56]
I am trying to integrate with datadog and I see that the details that I send to datadog appear as metrics in the datadog UI.. Is there a way to send events to datadog and not just as metrics

**Comment by nickdella** [comment]
Interesting idea, @arunbcodes .  As it stands, this library is focused on mapping Dropwizard Metrics constructs (like meter, timer, histogram, etc) to Datadog metric types (gauges and counters).  We also support Datadog's tagging feature via [our tag encoding scheme](https://github.com/coursera/metrics-datadog#tag-encoding-and-expansion).  

Do you have any thoughts as to how we could support metric to event conversion in this library without being too kludgy?  Maybe you could present the specific use case you have in mind and we could try to work backwards from there.

**Comment by nickdella** [comment]
Closing out some old tickets. @arunbcodes I know its been a while, but feel free to reopen if you have something more concrete per my previous comment.
