### ISSUE TITLE
Remove Error Logging from DatadogReporter

### ISSUE THREAD

**Issue by ZoharShayHFY** [coursera/metrics-datadog#58]
Hello,

First kudos; we use the DatadogReporter heavily in production providing critical alerts and very helpful metrics sampling across hundreds of hosts. It works great!

One tiny issue we have is that, at least according to our experience, sometimes the Datadog backend fails to receive metrics returning a 504 Bad Gateway HTTP error response. This is rare but happens. Since we have other means to verify that sufficient samples arrive (Setup Alert if Data is missing in Datadog) this is not considered an error, possibly a warning but usually even lower priority.

Also across our systems we setup any log error entry to trigger alerts which the team is expected to respond to. This works across all our system without false alarms except for the LOG.error report in DatadogReporter (org.coursera.metrics.datadog.DatadogReporter#report).

Is it possible that you replace the call to Log.error in report with a call to an exception consumer or "callback" passed during reporter build flow where the default implementation is Log.error?

If so that would be great help as we otherwise like to avoid silencing ERROR logging for third party libraries also because we would like to see such errors during tests and dev.

Thank you!

Zohar

**Comment by nickdella** [comment]
@ZoharShayHFY Thanks for the feedback!  I agree that an error callback would be a reasonable and more flexible approach for exception handling in `DatadogReporter`. Your PR would be most welcome :)

Question for you: as a workaround, would it possible with your logging framework to bump the log level to `FATAL` for only the `org.coursera.metrics.datadog` category?  Or is making that configuration change too onerous or error-prone?

**Comment by ZoharShayHFY** [comment]
Reducing `org.coursera.metrics.datadog` verbosity to `FATAL` is a no hassle workaround (we are using SLF4J over Logback).

**Comment by nickdella** [comment]
Sounds good, @ZoharShayHFY !  I'll close this issue out for now, but I'd be happy to re-open if anyone else is interested in a fix or has more ideas.  Either way, I'd be happy to entertain a PR for this if someone is willing to submit one.
