### ISSUE TITLE
UdpTransport is not working

### ISSUE THREAD

**Issue by srini-daruna** [coursera/metrics-datadog#63]
Hi, 

I am trying to send the metrics to dogstatsd using udptransport process.

```
val udpTransaport = new UdpTransport.Builder().withStatsdHost("localhost").withPort(8125).build()
    
    val tags = new ArrayList[String]();
    tags.add("test4:srini");
    tags.add("version:1.0.0");

    for (a <- 1 to 4) {
      println("sending metrics using udp reporter")
      val request = udpTransaport.prepare()
      val counter = new DatadogCounter("srini.test.78910", scala.util.Random.nextInt(1000), System.currentTimeMillis() / 1000, "9801a79a5063", tags);
      request.addCounter(counter)
      request.send()
    }
```

1) I could not see metrics in datadog. 
2) I could not see any messages in the dogstats.log file. 
3) My dogstats is running at 8125 port and checked every thing and can confirm it is running

Is there any thing that i am missing.?
I could not find examples in the tests as well for udptransport.

Is there a way to confirm that my messages are being sent to the host at least.?

**Comment by nickdella** [comment]
Hi @srini-daruna !  You're using `UdpTransport` directly in your example.  I'm assuming this is a deeper debugging path you've taken i.e. you've already tried setting up a `DatadogReporter` per the README?  If so, could you provide more information about your environment? Are you running in Docker by any chance? If so, see #52
