### ISSUE TITLE
DatadogReporter stops reporting to datadog of remaining metric data after throwing Exception during reporting process

### ISSUE THREAD

**Issue by waldemar-schneider** [coursera/metrics-datadog#64]
Hi guys,

we experienced in the past that some metrics were not reported, after some specific metrics (in our case a gauge, which counts some data) threw an error.

The specific class which is responsible: https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java#L71
If one of the given metrics throws any exception, the other metrics reporter are stopped.

**Comment by nickdella** [comment]
Thanks for the report, @waldemar-schneider !  Indeed, in the current design, every batch of metrics (sent every 10 seconds by default) is delivered atomically; either all metrics are sent or none.  We expect all your metrics to report something and not throw exceptions.

For now, if your gauge is throwing an exception, one workaround would be to catch it and report some error sentinel value like `-1`.  We could possibly do this in the reporter, but it would require additional configuration/complexity to decide how to handle errors (fail the batch, don't report that metric or report a sentinel value for that metric). I'm of the opinion that this is better handled by the application, but I'm open to suggestions/votes.

**Comment by codesimplicity** [comment]
Why would you need a sentinel value? The reporter could simply skip that metric.
This would mean no data would be reported for this metric but all others would be sent to Datadog.

IMHO this would be far better than skipping all metrics what happens currently.

After having looked into this more closely I see two things:
1. there already is a sentinel value: if a gauge would return `null` the reporter would ignore it (see `DatadogReporter#reportGauge`)
1. as this issue should only occur for gauges, it should be easy to catch exceptions when calling `gauge.getValue()` (again in `DatadogReporter#reportGauge`)


We will probably try to amend all of out gauges to make sure they catch exceptions and return `null` to prevent the 'no metrics reported' issue for the future.

Still it would be nice if the reporter would handle that. We'll create a PR...
