### ISSUE TITLE
DataDog HttpTransport: Compress postBody

### ISSUE THREAD

**Issue by neurolabs** [coursera/metrics-datadog#78]
Hi,

I recently ran into the 3MB limit on DDs API for posting metrics. They told me that their API allows for a compressed payload (see https://github.com/DataDog/dd-agent/blob/00bed41fa3c64824098761b1522c91cdfda43e65/emitter.py#L102). I spiked an implementation. Before I open a pull request against your repository, could we agree on:

* in the pom, the source and target compatibility is set to java 1.5. Would it be ok to raise this? Some interesting Deflate-related stuff came in with 1.6, apache commons compress sets 1.7. Would you prefer using JDK internal stuff, or could I pull in a dependency?
* Would it be ok to always compress, or should there be an option? I think compression should be the only choice (doesn't hurt much with small payloads, compression happens seldomly and is fast).

Any other thoughts?

**Comment by matlockx** [comment]
Last time we tried send compressed data in a golang client, the response was something 2ish but the Metrics never occurred in datadog. After raising that to them the continued to reply with comments from the api doc. I would test it with the python implementation first ;) we came up with a splitting solution: splitting the payload in 2.5 mb chunks and then doing one request per chunk.

**Comment by nickdella** [comment]
@neurolabs Thanks for the idea. I think compression will help quite a bit in addressing 3 MB limit. Metrics prefixes, tags, host names, timestamps are quite repetitive in the JSON request body. Regarding your particular questions:

> in the pom, the source and target compatibility is set to java 1.5
> Would you prefer using JDK internal stuff, or could I pull in a dependency?

I'd prefer to keep dependencies lean if it's not terribly burdensome to work with the JDK compression library. Hence, a bump to 1.6 target compatibility should be sufficient. Let me know if that works for you.

> Would it be ok to always compress, or should there be an option?

While we've generally tried to make the library highly configurable, I tend to agree that this particular improvement shouldn't have a noticeable performance impact given it runs just once every 10 seconds on a relatively small payload.  That said, it's pretty easy to set up a configuration flag in the code, so I'll leave it up to you.

**Comment by neurolabs** [comment]
@matlockx I get a 202 `{"status": "ok"}`, and I see the metrics in datadog.

@nickdella your answers are fine, I'll prepare the pull request accordingly.

**Comment by nickdella** [comment]
Thanks for the PR, @neurolabs ! I just pushed version `1.1.13` to maven central
