### ISSUE TITLE
Documentation for correct Datadog in-app metric metadata is greatly needed

### ISSUE THREAD

**Issue by mbroomfield-r7** [coursera/metrics-datadog#82]
We have been using an old version of metrics-datadog (1.1.1) and want to update to the latest version (1.1.13).

However, between those versions metric-datadog has changed how it uploads metrics of different types. Since the metric metadata is only set once, this causes our metrics to look out of whack, as metrics now have the wrong (or maybe correct but different) type.

We would love to update but we would like to have a set of rules for how to configure our metric metadata; we heavily use datadog alarms, so correct metric reporting is important.

Here, Datadog supplies a table which shows how a call to a certain metric type should be configured: https://help.datadoghq.com/hc/en-us/articles/206955236-Metric-types-in-Datadog

A similar table would be a huge win for this library. Either that, or metrics-datadog should match the same behavior as dogstatsd.

I've skimmed through the commit history looking for commits where this change might have happened. I see https://github.com/coursera/metrics-datadog/commit/08ee26218c59827ba73630c990c8a067a07ae542
but I'm not sure if other metric type reporting changes have occurred.

**Comment by nickdella** [comment]
Hi @mbroomfield-r7 ! The commit you referenced is one such change over the last year or so. See #22, #32, #45 and #47  for additional context on the metric typing dilemma. 

As of right now per #47 , every Dropwizard metric type is being reported as a Datadog `Gauge` to Datadog.  You can follow the code in `[DatadogReporter](https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java#L89)` and find that every branch ends in a `new DatadogGauge(...)` being sent.
