### ISSUE TITLE
Update to latest Metrics version

### ISSUE THREAD

**Issue by lomigmegard** [coursera/metrics-datadog#88]
The new major version `4.0.1` has been released: 
http://metrics.dropwizard.io/4.0.0/about/release-notes.html

Note that Java 1.8 is now required.

A new version `1.2.2` of Dropwizard is also available:
https://github.com/dropwizard/dropwizard/releases

Also require Java 1.8.

**Comment by dguo-coursera** [comment]
Thanks for the PR @lomigmegard. Will take a look soon.
