### ISSUE TITLE
When is 2.0 going to be released?

### ISSUE THREAD

**Issue by seanstaley** [coursera/metrics-datadog#94]
Hello,

I was wondering when this library's 2.0 version will be released? 

I attempted to upgrade my application to Dropwizard-metrics 4+ a few months ago, but ran into some issues with this library and the upgraded metric library. I just noticed that the libraries were upgraded here, so I thought I would ask. 

Thanks!

P.S. Looks like `dropwizard-metrics` 5.0 is going to be released in the near future too. 😄

**Comment by dguo-coursera** [comment]
Sorry about the delay. We've published 2.0.0-RC1 and will be testing it with our production load after 1.1.14-RC1.
